# fly.toml app configuration file generated for cogency on 2025-07-13T11:24:17+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cogency'
primary_region = 'syd'

[build]

[env]
  PORT = '4321'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/dist'
  url_prefix = '/'
